default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: 'yiledcalculator_dev'

test:
  <<: *default
  database: 'yiledcalculator_test'
